### ISSUE TITLE
Is it possible to use this in vscode?

### ISSUE THREAD

**Issue by voronoipotato** [the-gamma/thegamma-script#2]
I was thinking it might be useful if this could be used with vscode as an extension. Either way fantastic work this is extremely interesting.

**Comment by tpetricek** [comment]
Thanks! The code implements bindings for the Monaco editor, which is behind VS Code too. My current interest with this is currently focused more on the web, so I do not have any immediate plans for this - but I'll be happy to help if this is something you'd be interested in doing :-)

(Although I'll be on holidays for the next two weeks...)
